/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as CenterGroveRouteImport } from './routes/center-grove'
import { Route as ButlerRouteImport } from './routes/butler'
import { Route as AssaRouteImport } from './routes/assa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegacyIndexRouteImport } from './routes/legacy.index'
import { Route as CenterGroveIndexRouteImport } from './routes/center-grove.index'
import { Route as ButlerIndexRouteImport } from './routes/butler.index'
import { Route as AssaIndexRouteImport } from './routes/assa.index'
import { Route as LegacyTeamCardRouteImport } from './routes/legacy.team-card'
import { Route as LegacyCartRouteImport } from './routes/legacy.cart'
import { Route as CenterGroveTeamCardRouteImport } from './routes/center-grove.team-card'
import { Route as CenterGroveCartRouteImport } from './routes/center-grove.cart'
import { Route as ButlerTeamCardRouteImport } from './routes/butler.team-card'
import { Route as ButlerCartRouteImport } from './routes/butler.cart'
import { Route as AssaTeamCardRouteImport } from './routes/assa.team-card'
import { Route as AssaCartRouteImport } from './routes/assa.cart'
import { Route as LegacySponsorsIndexRouteImport } from './routes/legacy.sponsors.index'
import { Route as LegacyShopIndexRouteImport } from './routes/legacy.shop.index'
import { Route as LegacyOrgsIndexRouteImport } from './routes/legacy.orgs.index'
import { Route as CenterGroveSponsorsIndexRouteImport } from './routes/center-grove.sponsors.index'
import { Route as CenterGroveShopIndexRouteImport } from './routes/center-grove.shop.index'
import { Route as CenterGroveOrgsIndexRouteImport } from './routes/center-grove.orgs.index'
import { Route as ButlerTeamsIndexRouteImport } from './routes/butler.teams.index'
import { Route as ButlerSponsorsIndexRouteImport } from './routes/butler.sponsors.index'
import { Route as ButlerShopIndexRouteImport } from './routes/butler.shop.index'
import { Route as AssaSponsorsIndexRouteImport } from './routes/assa.sponsors.index'
import { Route as AssaShopIndexRouteImport } from './routes/assa.shop.index'
import { Route as AssaOrgsIndexRouteImport } from './routes/assa.orgs.index'
import { Route as LegacySponsorsSlugRouteImport } from './routes/legacy.sponsors.$slug'
import { Route as LegacyShopCategoryRouteImport } from './routes/legacy.shop.$category'
import { Route as LegacyProductSlugRouteImport } from './routes/legacy.product.$slug'
import { Route as LegacyOrgsOrgRouteImport } from './routes/legacy.orgs.$org'
import { Route as CenterGroveSponsorsSlugRouteImport } from './routes/center-grove.sponsors.$slug'
import { Route as CenterGroveShopCategoryRouteImport } from './routes/center-grove.shop.$category'
import { Route as CenterGroveProductSlugRouteImport } from './routes/center-grove.product.$slug'
import { Route as CenterGroveOrgsOrgRouteImport } from './routes/center-grove.orgs.$org'
import { Route as ButlerTeamsSportRouteImport } from './routes/butler.teams.$sport'
import { Route as ButlerSponsorsSlugRouteImport } from './routes/butler.sponsors.$slug'
import { Route as ButlerShopCategoryRouteImport } from './routes/butler.shop.$category'
import { Route as ButlerProductSlugRouteImport } from './routes/butler.product.$slug'
import { Route as AssaSponsorsSlugRouteImport } from './routes/assa.sponsors.$slug'
import { Route as AssaShopCategoryRouteImport } from './routes/assa.shop.$category'
import { Route as AssaProductSlugRouteImport } from './routes/assa.product.$slug'
import { Route as AssaOrgsOrgRouteImport } from './routes/assa.orgs.$org'
import { Route as LegacyOrgsOrgTeamRouteImport } from './routes/legacy.orgs.$org.$team'
import { Route as CenterGroveSponsorsSlugClaimRouteImport } from './routes/center-grove.sponsors.$slug.claim'
import { Route as CenterGroveOrgsOrgTeamRouteImport } from './routes/center-grove.orgs.$org.$team'
import { Route as ButlerTeamsSportPlayerRouteImport } from './routes/butler.teams.$sport.$player'
import { Route as ButlerSponsorsSlugClaimRouteImport } from './routes/butler.sponsors.$slug.claim'
import { Route as AssaOrgsOrgTeamRouteImport } from './routes/assa.orgs.$org.$team'
import { Route as LegacyOrgsOrgTeamPlayerRouteImport } from './routes/legacy.orgs.$org.$team.$player'
import { Route as CenterGroveOrgsOrgTeamPlayerRouteImport } from './routes/center-grove.orgs.$org.$team.$player'
import { Route as AssaOrgsOrgTeamPlayerRouteImport } from './routes/assa.orgs.$org.$team.$player'

const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterGroveRoute = CenterGroveRouteImport.update({
  id: '/center-grove',
  path: '/center-grove',
  getParentRoute: () => rootRouteImport,
} as any)
const ButlerRoute = ButlerRouteImport.update({
  id: '/butler',
  path: '/butler',
  getParentRoute: () => rootRouteImport,
} as any)
const AssaRoute = AssaRouteImport.update({
  id: '/assa',
  path: '/assa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyRoute,
} as any)
const CenterGroveIndexRoute = CenterGroveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CenterGroveRoute,
} as any)
const ButlerIndexRoute = ButlerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ButlerRoute,
} as any)
const AssaIndexRoute = AssaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssaRoute,
} as any)
const LegacyTeamCardRoute = LegacyTeamCardRouteImport.update({
  id: '/team-card',
  path: '/team-card',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyCartRoute = LegacyCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LegacyRoute,
} as any)
const CenterGroveTeamCardRoute = CenterGroveTeamCardRouteImport.update({
  id: '/team-card',
  path: '/team-card',
  getParentRoute: () => CenterGroveRoute,
} as any)
const CenterGroveCartRoute = CenterGroveCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CenterGroveRoute,
} as any)
const ButlerTeamCardRoute = ButlerTeamCardRouteImport.update({
  id: '/team-card',
  path: '/team-card',
  getParentRoute: () => ButlerRoute,
} as any)
const ButlerCartRoute = ButlerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ButlerRoute,
} as any)
const AssaTeamCardRoute = AssaTeamCardRouteImport.update({
  id: '/team-card',
  path: '/team-card',
  getParentRoute: () => AssaRoute,
} as any)
const AssaCartRoute = AssaCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AssaRoute,
} as any)
const LegacySponsorsIndexRoute = LegacySponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyShopIndexRoute = LegacyShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyOrgsIndexRoute = LegacyOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => LegacyRoute,
} as any)
const CenterGroveSponsorsIndexRoute =
  CenterGroveSponsorsIndexRouteImport.update({
    id: '/sponsors/',
    path: '/sponsors/',
    getParentRoute: () => CenterGroveRoute,
  } as any)
const CenterGroveShopIndexRoute = CenterGroveShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => CenterGroveRoute,
} as any)
const CenterGroveOrgsIndexRoute = CenterGroveOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => CenterGroveRoute,
} as any)
const ButlerTeamsIndexRoute = ButlerTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => ButlerRoute,
} as any)
const ButlerSponsorsIndexRoute = ButlerSponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => ButlerRoute,
} as any)
const ButlerShopIndexRoute = ButlerShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => ButlerRoute,
} as any)
const AssaSponsorsIndexRoute = AssaSponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => AssaRoute,
} as any)
const AssaShopIndexRoute = AssaShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AssaRoute,
} as any)
const AssaOrgsIndexRoute = AssaOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AssaRoute,
} as any)
const LegacySponsorsSlugRoute = LegacySponsorsSlugRouteImport.update({
  id: '/sponsors/$slug',
  path: '/sponsors/$slug',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyShopCategoryRoute = LegacyShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyProductSlugRoute = LegacyProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyOrgsOrgRoute = LegacyOrgsOrgRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => LegacyRoute,
} as any)
const CenterGroveSponsorsSlugRoute = CenterGroveSponsorsSlugRouteImport.update({
  id: '/sponsors/$slug',
  path: '/sponsors/$slug',
  getParentRoute: () => CenterGroveRoute,
} as any)
const CenterGroveShopCategoryRoute = CenterGroveShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => CenterGroveRoute,
} as any)
const CenterGroveProductSlugRoute = CenterGroveProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => CenterGroveRoute,
} as any)
const CenterGroveOrgsOrgRoute = CenterGroveOrgsOrgRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => CenterGroveRoute,
} as any)
const ButlerTeamsSportRoute = ButlerTeamsSportRouteImport.update({
  id: '/teams/$sport',
  path: '/teams/$sport',
  getParentRoute: () => ButlerRoute,
} as any)
const ButlerSponsorsSlugRoute = ButlerSponsorsSlugRouteImport.update({
  id: '/sponsors/$slug',
  path: '/sponsors/$slug',
  getParentRoute: () => ButlerRoute,
} as any)
const ButlerShopCategoryRoute = ButlerShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => ButlerRoute,
} as any)
const ButlerProductSlugRoute = ButlerProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => ButlerRoute,
} as any)
const AssaSponsorsSlugRoute = AssaSponsorsSlugRouteImport.update({
  id: '/sponsors/$slug',
  path: '/sponsors/$slug',
  getParentRoute: () => AssaRoute,
} as any)
const AssaShopCategoryRoute = AssaShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => AssaRoute,
} as any)
const AssaProductSlugRoute = AssaProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => AssaRoute,
} as any)
const AssaOrgsOrgRoute = AssaOrgsOrgRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => AssaRoute,
} as any)
const LegacyOrgsOrgTeamRoute = LegacyOrgsOrgTeamRouteImport.update({
  id: '/$team',
  path: '/$team',
  getParentRoute: () => LegacyOrgsOrgRoute,
} as any)
const CenterGroveSponsorsSlugClaimRoute =
  CenterGroveSponsorsSlugClaimRouteImport.update({
    id: '/claim',
    path: '/claim',
    getParentRoute: () => CenterGroveSponsorsSlugRoute,
  } as any)
const CenterGroveOrgsOrgTeamRoute = CenterGroveOrgsOrgTeamRouteImport.update({
  id: '/$team',
  path: '/$team',
  getParentRoute: () => CenterGroveOrgsOrgRoute,
} as any)
const ButlerTeamsSportPlayerRoute = ButlerTeamsSportPlayerRouteImport.update({
  id: '/$player',
  path: '/$player',
  getParentRoute: () => ButlerTeamsSportRoute,
} as any)
const ButlerSponsorsSlugClaimRoute = ButlerSponsorsSlugClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ButlerSponsorsSlugRoute,
} as any)
const AssaOrgsOrgTeamRoute = AssaOrgsOrgTeamRouteImport.update({
  id: '/$team',
  path: '/$team',
  getParentRoute: () => AssaOrgsOrgRoute,
} as any)
const LegacyOrgsOrgTeamPlayerRoute = LegacyOrgsOrgTeamPlayerRouteImport.update({
  id: '/$player',
  path: '/$player',
  getParentRoute: () => LegacyOrgsOrgTeamRoute,
} as any)
const CenterGroveOrgsOrgTeamPlayerRoute =
  CenterGroveOrgsOrgTeamPlayerRouteImport.update({
    id: '/$player',
    path: '/$player',
    getParentRoute: () => CenterGroveOrgsOrgTeamRoute,
  } as any)
const AssaOrgsOrgTeamPlayerRoute = AssaOrgsOrgTeamPlayerRouteImport.update({
  id: '/$player',
  path: '/$player',
  getParentRoute: () => AssaOrgsOrgTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assa': typeof AssaRouteWithChildren
  '/butler': typeof ButlerRouteWithChildren
  '/center-grove': typeof CenterGroveRouteWithChildren
  '/legacy': typeof LegacyRouteWithChildren
  '/assa/cart': typeof AssaCartRoute
  '/assa/team-card': typeof AssaTeamCardRoute
  '/butler/cart': typeof ButlerCartRoute
  '/butler/team-card': typeof ButlerTeamCardRoute
  '/center-grove/cart': typeof CenterGroveCartRoute
  '/center-grove/team-card': typeof CenterGroveTeamCardRoute
  '/legacy/cart': typeof LegacyCartRoute
  '/legacy/team-card': typeof LegacyTeamCardRoute
  '/assa/': typeof AssaIndexRoute
  '/butler/': typeof ButlerIndexRoute
  '/center-grove/': typeof CenterGroveIndexRoute
  '/legacy/': typeof LegacyIndexRoute
  '/assa/orgs/$org': typeof AssaOrgsOrgRouteWithChildren
  '/assa/product/$slug': typeof AssaProductSlugRoute
  '/assa/shop/$category': typeof AssaShopCategoryRoute
  '/assa/sponsors/$slug': typeof AssaSponsorsSlugRoute
  '/butler/product/$slug': typeof ButlerProductSlugRoute
  '/butler/shop/$category': typeof ButlerShopCategoryRoute
  '/butler/sponsors/$slug': typeof ButlerSponsorsSlugRouteWithChildren
  '/butler/teams/$sport': typeof ButlerTeamsSportRouteWithChildren
  '/center-grove/orgs/$org': typeof CenterGroveOrgsOrgRouteWithChildren
  '/center-grove/product/$slug': typeof CenterGroveProductSlugRoute
  '/center-grove/shop/$category': typeof CenterGroveShopCategoryRoute
  '/center-grove/sponsors/$slug': typeof CenterGroveSponsorsSlugRouteWithChildren
  '/legacy/orgs/$org': typeof LegacyOrgsOrgRouteWithChildren
  '/legacy/product/$slug': typeof LegacyProductSlugRoute
  '/legacy/shop/$category': typeof LegacyShopCategoryRoute
  '/legacy/sponsors/$slug': typeof LegacySponsorsSlugRoute
  '/assa/orgs/': typeof AssaOrgsIndexRoute
  '/assa/shop/': typeof AssaShopIndexRoute
  '/assa/sponsors/': typeof AssaSponsorsIndexRoute
  '/butler/shop/': typeof ButlerShopIndexRoute
  '/butler/sponsors/': typeof ButlerSponsorsIndexRoute
  '/butler/teams/': typeof ButlerTeamsIndexRoute
  '/center-grove/orgs/': typeof CenterGroveOrgsIndexRoute
  '/center-grove/shop/': typeof CenterGroveShopIndexRoute
  '/center-grove/sponsors/': typeof CenterGroveSponsorsIndexRoute
  '/legacy/orgs/': typeof LegacyOrgsIndexRoute
  '/legacy/shop/': typeof LegacyShopIndexRoute
  '/legacy/sponsors/': typeof LegacySponsorsIndexRoute
  '/assa/orgs/$org/$team': typeof AssaOrgsOrgTeamRouteWithChildren
  '/butler/sponsors/$slug/claim': typeof ButlerSponsorsSlugClaimRoute
  '/butler/teams/$sport/$player': typeof ButlerTeamsSportPlayerRoute
  '/center-grove/orgs/$org/$team': typeof CenterGroveOrgsOrgTeamRouteWithChildren
  '/center-grove/sponsors/$slug/claim': typeof CenterGroveSponsorsSlugClaimRoute
  '/legacy/orgs/$org/$team': typeof LegacyOrgsOrgTeamRouteWithChildren
  '/assa/orgs/$org/$team/$player': typeof AssaOrgsOrgTeamPlayerRoute
  '/center-grove/orgs/$org/$team/$player': typeof CenterGroveOrgsOrgTeamPlayerRoute
  '/legacy/orgs/$org/$team/$player': typeof LegacyOrgsOrgTeamPlayerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assa/cart': typeof AssaCartRoute
  '/assa/team-card': typeof AssaTeamCardRoute
  '/butler/cart': typeof ButlerCartRoute
  '/butler/team-card': typeof ButlerTeamCardRoute
  '/center-grove/cart': typeof CenterGroveCartRoute
  '/center-grove/team-card': typeof CenterGroveTeamCardRoute
  '/legacy/cart': typeof LegacyCartRoute
  '/legacy/team-card': typeof LegacyTeamCardRoute
  '/assa': typeof AssaIndexRoute
  '/butler': typeof ButlerIndexRoute
  '/center-grove': typeof CenterGroveIndexRoute
  '/legacy': typeof LegacyIndexRoute
  '/assa/orgs/$org': typeof AssaOrgsOrgRouteWithChildren
  '/assa/product/$slug': typeof AssaProductSlugRoute
  '/assa/shop/$category': typeof AssaShopCategoryRoute
  '/assa/sponsors/$slug': typeof AssaSponsorsSlugRoute
  '/butler/product/$slug': typeof ButlerProductSlugRoute
  '/butler/shop/$category': typeof ButlerShopCategoryRoute
  '/butler/sponsors/$slug': typeof ButlerSponsorsSlugRouteWithChildren
  '/butler/teams/$sport': typeof ButlerTeamsSportRouteWithChildren
  '/center-grove/orgs/$org': typeof CenterGroveOrgsOrgRouteWithChildren
  '/center-grove/product/$slug': typeof CenterGroveProductSlugRoute
  '/center-grove/shop/$category': typeof CenterGroveShopCategoryRoute
  '/center-grove/sponsors/$slug': typeof CenterGroveSponsorsSlugRouteWithChildren
  '/legacy/orgs/$org': typeof LegacyOrgsOrgRouteWithChildren
  '/legacy/product/$slug': typeof LegacyProductSlugRoute
  '/legacy/shop/$category': typeof LegacyShopCategoryRoute
  '/legacy/sponsors/$slug': typeof LegacySponsorsSlugRoute
  '/assa/orgs': typeof AssaOrgsIndexRoute
  '/assa/shop': typeof AssaShopIndexRoute
  '/assa/sponsors': typeof AssaSponsorsIndexRoute
  '/butler/shop': typeof ButlerShopIndexRoute
  '/butler/sponsors': typeof ButlerSponsorsIndexRoute
  '/butler/teams': typeof ButlerTeamsIndexRoute
  '/center-grove/orgs': typeof CenterGroveOrgsIndexRoute
  '/center-grove/shop': typeof CenterGroveShopIndexRoute
  '/center-grove/sponsors': typeof CenterGroveSponsorsIndexRoute
  '/legacy/orgs': typeof LegacyOrgsIndexRoute
  '/legacy/shop': typeof LegacyShopIndexRoute
  '/legacy/sponsors': typeof LegacySponsorsIndexRoute
  '/assa/orgs/$org/$team': typeof AssaOrgsOrgTeamRouteWithChildren
  '/butler/sponsors/$slug/claim': typeof ButlerSponsorsSlugClaimRoute
  '/butler/teams/$sport/$player': typeof ButlerTeamsSportPlayerRoute
  '/center-grove/orgs/$org/$team': typeof CenterGroveOrgsOrgTeamRouteWithChildren
  '/center-grove/sponsors/$slug/claim': typeof CenterGroveSponsorsSlugClaimRoute
  '/legacy/orgs/$org/$team': typeof LegacyOrgsOrgTeamRouteWithChildren
  '/assa/orgs/$org/$team/$player': typeof AssaOrgsOrgTeamPlayerRoute
  '/center-grove/orgs/$org/$team/$player': typeof CenterGroveOrgsOrgTeamPlayerRoute
  '/legacy/orgs/$org/$team/$player': typeof LegacyOrgsOrgTeamPlayerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assa': typeof AssaRouteWithChildren
  '/butler': typeof ButlerRouteWithChildren
  '/center-grove': typeof CenterGroveRouteWithChildren
  '/legacy': typeof LegacyRouteWithChildren
  '/assa/cart': typeof AssaCartRoute
  '/assa/team-card': typeof AssaTeamCardRoute
  '/butler/cart': typeof ButlerCartRoute
  '/butler/team-card': typeof ButlerTeamCardRoute
  '/center-grove/cart': typeof CenterGroveCartRoute
  '/center-grove/team-card': typeof CenterGroveTeamCardRoute
  '/legacy/cart': typeof LegacyCartRoute
  '/legacy/team-card': typeof LegacyTeamCardRoute
  '/assa/': typeof AssaIndexRoute
  '/butler/': typeof ButlerIndexRoute
  '/center-grove/': typeof CenterGroveIndexRoute
  '/legacy/': typeof LegacyIndexRoute
  '/assa/orgs/$org': typeof AssaOrgsOrgRouteWithChildren
  '/assa/product/$slug': typeof AssaProductSlugRoute
  '/assa/shop/$category': typeof AssaShopCategoryRoute
  '/assa/sponsors/$slug': typeof AssaSponsorsSlugRoute
  '/butler/product/$slug': typeof ButlerProductSlugRoute
  '/butler/shop/$category': typeof ButlerShopCategoryRoute
  '/butler/sponsors/$slug': typeof ButlerSponsorsSlugRouteWithChildren
  '/butler/teams/$sport': typeof ButlerTeamsSportRouteWithChildren
  '/center-grove/orgs/$org': typeof CenterGroveOrgsOrgRouteWithChildren
  '/center-grove/product/$slug': typeof CenterGroveProductSlugRoute
  '/center-grove/shop/$category': typeof CenterGroveShopCategoryRoute
  '/center-grove/sponsors/$slug': typeof CenterGroveSponsorsSlugRouteWithChildren
  '/legacy/orgs/$org': typeof LegacyOrgsOrgRouteWithChildren
  '/legacy/product/$slug': typeof LegacyProductSlugRoute
  '/legacy/shop/$category': typeof LegacyShopCategoryRoute
  '/legacy/sponsors/$slug': typeof LegacySponsorsSlugRoute
  '/assa/orgs/': typeof AssaOrgsIndexRoute
  '/assa/shop/': typeof AssaShopIndexRoute
  '/assa/sponsors/': typeof AssaSponsorsIndexRoute
  '/butler/shop/': typeof ButlerShopIndexRoute
  '/butler/sponsors/': typeof ButlerSponsorsIndexRoute
  '/butler/teams/': typeof ButlerTeamsIndexRoute
  '/center-grove/orgs/': typeof CenterGroveOrgsIndexRoute
  '/center-grove/shop/': typeof CenterGroveShopIndexRoute
  '/center-grove/sponsors/': typeof CenterGroveSponsorsIndexRoute
  '/legacy/orgs/': typeof LegacyOrgsIndexRoute
  '/legacy/shop/': typeof LegacyShopIndexRoute
  '/legacy/sponsors/': typeof LegacySponsorsIndexRoute
  '/assa/orgs/$org/$team': typeof AssaOrgsOrgTeamRouteWithChildren
  '/butler/sponsors/$slug/claim': typeof ButlerSponsorsSlugClaimRoute
  '/butler/teams/$sport/$player': typeof ButlerTeamsSportPlayerRoute
  '/center-grove/orgs/$org/$team': typeof CenterGroveOrgsOrgTeamRouteWithChildren
  '/center-grove/sponsors/$slug/claim': typeof CenterGroveSponsorsSlugClaimRoute
  '/legacy/orgs/$org/$team': typeof LegacyOrgsOrgTeamRouteWithChildren
  '/assa/orgs/$org/$team/$player': typeof AssaOrgsOrgTeamPlayerRoute
  '/center-grove/orgs/$org/$team/$player': typeof CenterGroveOrgsOrgTeamPlayerRoute
  '/legacy/orgs/$org/$team/$player': typeof LegacyOrgsOrgTeamPlayerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assa'
    | '/butler'
    | '/center-grove'
    | '/legacy'
    | '/assa/cart'
    | '/assa/team-card'
    | '/butler/cart'
    | '/butler/team-card'
    | '/center-grove/cart'
    | '/center-grove/team-card'
    | '/legacy/cart'
    | '/legacy/team-card'
    | '/assa/'
    | '/butler/'
    | '/center-grove/'
    | '/legacy/'
    | '/assa/orgs/$org'
    | '/assa/product/$slug'
    | '/assa/shop/$category'
    | '/assa/sponsors/$slug'
    | '/butler/product/$slug'
    | '/butler/shop/$category'
    | '/butler/sponsors/$slug'
    | '/butler/teams/$sport'
    | '/center-grove/orgs/$org'
    | '/center-grove/product/$slug'
    | '/center-grove/shop/$category'
    | '/center-grove/sponsors/$slug'
    | '/legacy/orgs/$org'
    | '/legacy/product/$slug'
    | '/legacy/shop/$category'
    | '/legacy/sponsors/$slug'
    | '/assa/orgs/'
    | '/assa/shop/'
    | '/assa/sponsors/'
    | '/butler/shop/'
    | '/butler/sponsors/'
    | '/butler/teams/'
    | '/center-grove/orgs/'
    | '/center-grove/shop/'
    | '/center-grove/sponsors/'
    | '/legacy/orgs/'
    | '/legacy/shop/'
    | '/legacy/sponsors/'
    | '/assa/orgs/$org/$team'
    | '/butler/sponsors/$slug/claim'
    | '/butler/teams/$sport/$player'
    | '/center-grove/orgs/$org/$team'
    | '/center-grove/sponsors/$slug/claim'
    | '/legacy/orgs/$org/$team'
    | '/assa/orgs/$org/$team/$player'
    | '/center-grove/orgs/$org/$team/$player'
    | '/legacy/orgs/$org/$team/$player'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assa/cart'
    | '/assa/team-card'
    | '/butler/cart'
    | '/butler/team-card'
    | '/center-grove/cart'
    | '/center-grove/team-card'
    | '/legacy/cart'
    | '/legacy/team-card'
    | '/assa'
    | '/butler'
    | '/center-grove'
    | '/legacy'
    | '/assa/orgs/$org'
    | '/assa/product/$slug'
    | '/assa/shop/$category'
    | '/assa/sponsors/$slug'
    | '/butler/product/$slug'
    | '/butler/shop/$category'
    | '/butler/sponsors/$slug'
    | '/butler/teams/$sport'
    | '/center-grove/orgs/$org'
    | '/center-grove/product/$slug'
    | '/center-grove/shop/$category'
    | '/center-grove/sponsors/$slug'
    | '/legacy/orgs/$org'
    | '/legacy/product/$slug'
    | '/legacy/shop/$category'
    | '/legacy/sponsors/$slug'
    | '/assa/orgs'
    | '/assa/shop'
    | '/assa/sponsors'
    | '/butler/shop'
    | '/butler/sponsors'
    | '/butler/teams'
    | '/center-grove/orgs'
    | '/center-grove/shop'
    | '/center-grove/sponsors'
    | '/legacy/orgs'
    | '/legacy/shop'
    | '/legacy/sponsors'
    | '/assa/orgs/$org/$team'
    | '/butler/sponsors/$slug/claim'
    | '/butler/teams/$sport/$player'
    | '/center-grove/orgs/$org/$team'
    | '/center-grove/sponsors/$slug/claim'
    | '/legacy/orgs/$org/$team'
    | '/assa/orgs/$org/$team/$player'
    | '/center-grove/orgs/$org/$team/$player'
    | '/legacy/orgs/$org/$team/$player'
  id:
    | '__root__'
    | '/'
    | '/assa'
    | '/butler'
    | '/center-grove'
    | '/legacy'
    | '/assa/cart'
    | '/assa/team-card'
    | '/butler/cart'
    | '/butler/team-card'
    | '/center-grove/cart'
    | '/center-grove/team-card'
    | '/legacy/cart'
    | '/legacy/team-card'
    | '/assa/'
    | '/butler/'
    | '/center-grove/'
    | '/legacy/'
    | '/assa/orgs/$org'
    | '/assa/product/$slug'
    | '/assa/shop/$category'
    | '/assa/sponsors/$slug'
    | '/butler/product/$slug'
    | '/butler/shop/$category'
    | '/butler/sponsors/$slug'
    | '/butler/teams/$sport'
    | '/center-grove/orgs/$org'
    | '/center-grove/product/$slug'
    | '/center-grove/shop/$category'
    | '/center-grove/sponsors/$slug'
    | '/legacy/orgs/$org'
    | '/legacy/product/$slug'
    | '/legacy/shop/$category'
    | '/legacy/sponsors/$slug'
    | '/assa/orgs/'
    | '/assa/shop/'
    | '/assa/sponsors/'
    | '/butler/shop/'
    | '/butler/sponsors/'
    | '/butler/teams/'
    | '/center-grove/orgs/'
    | '/center-grove/shop/'
    | '/center-grove/sponsors/'
    | '/legacy/orgs/'
    | '/legacy/shop/'
    | '/legacy/sponsors/'
    | '/assa/orgs/$org/$team'
    | '/butler/sponsors/$slug/claim'
    | '/butler/teams/$sport/$player'
    | '/center-grove/orgs/$org/$team'
    | '/center-grove/sponsors/$slug/claim'
    | '/legacy/orgs/$org/$team'
    | '/assa/orgs/$org/$team/$player'
    | '/center-grove/orgs/$org/$team/$player'
    | '/legacy/orgs/$org/$team/$player'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssaRoute: typeof AssaRouteWithChildren
  ButlerRoute: typeof ButlerRouteWithChildren
  CenterGroveRoute: typeof CenterGroveRouteWithChildren
  LegacyRoute: typeof LegacyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center-grove': {
      id: '/center-grove'
      path: '/center-grove'
      fullPath: '/center-grove'
      preLoaderRoute: typeof CenterGroveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/butler': {
      id: '/butler'
      path: '/butler'
      fullPath: '/butler'
      preLoaderRoute: typeof ButlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assa': {
      id: '/assa'
      path: '/assa'
      fullPath: '/assa'
      preLoaderRoute: typeof AssaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/': {
      id: '/legacy/'
      path: '/'
      fullPath: '/legacy/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/center-grove/': {
      id: '/center-grove/'
      path: '/'
      fullPath: '/center-grove/'
      preLoaderRoute: typeof CenterGroveIndexRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/butler/': {
      id: '/butler/'
      path: '/'
      fullPath: '/butler/'
      preLoaderRoute: typeof ButlerIndexRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/assa/': {
      id: '/assa/'
      path: '/'
      fullPath: '/assa/'
      preLoaderRoute: typeof AssaIndexRouteImport
      parentRoute: typeof AssaRoute
    }
    '/legacy/team-card': {
      id: '/legacy/team-card'
      path: '/team-card'
      fullPath: '/legacy/team-card'
      preLoaderRoute: typeof LegacyTeamCardRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/cart': {
      id: '/legacy/cart'
      path: '/cart'
      fullPath: '/legacy/cart'
      preLoaderRoute: typeof LegacyCartRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/center-grove/team-card': {
      id: '/center-grove/team-card'
      path: '/team-card'
      fullPath: '/center-grove/team-card'
      preLoaderRoute: typeof CenterGroveTeamCardRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/center-grove/cart': {
      id: '/center-grove/cart'
      path: '/cart'
      fullPath: '/center-grove/cart'
      preLoaderRoute: typeof CenterGroveCartRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/butler/team-card': {
      id: '/butler/team-card'
      path: '/team-card'
      fullPath: '/butler/team-card'
      preLoaderRoute: typeof ButlerTeamCardRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/butler/cart': {
      id: '/butler/cart'
      path: '/cart'
      fullPath: '/butler/cart'
      preLoaderRoute: typeof ButlerCartRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/assa/team-card': {
      id: '/assa/team-card'
      path: '/team-card'
      fullPath: '/assa/team-card'
      preLoaderRoute: typeof AssaTeamCardRouteImport
      parentRoute: typeof AssaRoute
    }
    '/assa/cart': {
      id: '/assa/cart'
      path: '/cart'
      fullPath: '/assa/cart'
      preLoaderRoute: typeof AssaCartRouteImport
      parentRoute: typeof AssaRoute
    }
    '/legacy/sponsors/': {
      id: '/legacy/sponsors/'
      path: '/sponsors'
      fullPath: '/legacy/sponsors/'
      preLoaderRoute: typeof LegacySponsorsIndexRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/shop/': {
      id: '/legacy/shop/'
      path: '/shop'
      fullPath: '/legacy/shop/'
      preLoaderRoute: typeof LegacyShopIndexRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/orgs/': {
      id: '/legacy/orgs/'
      path: '/orgs'
      fullPath: '/legacy/orgs/'
      preLoaderRoute: typeof LegacyOrgsIndexRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/center-grove/sponsors/': {
      id: '/center-grove/sponsors/'
      path: '/sponsors'
      fullPath: '/center-grove/sponsors/'
      preLoaderRoute: typeof CenterGroveSponsorsIndexRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/center-grove/shop/': {
      id: '/center-grove/shop/'
      path: '/shop'
      fullPath: '/center-grove/shop/'
      preLoaderRoute: typeof CenterGroveShopIndexRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/center-grove/orgs/': {
      id: '/center-grove/orgs/'
      path: '/orgs'
      fullPath: '/center-grove/orgs/'
      preLoaderRoute: typeof CenterGroveOrgsIndexRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/butler/teams/': {
      id: '/butler/teams/'
      path: '/teams'
      fullPath: '/butler/teams/'
      preLoaderRoute: typeof ButlerTeamsIndexRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/butler/sponsors/': {
      id: '/butler/sponsors/'
      path: '/sponsors'
      fullPath: '/butler/sponsors/'
      preLoaderRoute: typeof ButlerSponsorsIndexRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/butler/shop/': {
      id: '/butler/shop/'
      path: '/shop'
      fullPath: '/butler/shop/'
      preLoaderRoute: typeof ButlerShopIndexRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/assa/sponsors/': {
      id: '/assa/sponsors/'
      path: '/sponsors'
      fullPath: '/assa/sponsors/'
      preLoaderRoute: typeof AssaSponsorsIndexRouteImport
      parentRoute: typeof AssaRoute
    }
    '/assa/shop/': {
      id: '/assa/shop/'
      path: '/shop'
      fullPath: '/assa/shop/'
      preLoaderRoute: typeof AssaShopIndexRouteImport
      parentRoute: typeof AssaRoute
    }
    '/assa/orgs/': {
      id: '/assa/orgs/'
      path: '/orgs'
      fullPath: '/assa/orgs/'
      preLoaderRoute: typeof AssaOrgsIndexRouteImport
      parentRoute: typeof AssaRoute
    }
    '/legacy/sponsors/$slug': {
      id: '/legacy/sponsors/$slug'
      path: '/sponsors/$slug'
      fullPath: '/legacy/sponsors/$slug'
      preLoaderRoute: typeof LegacySponsorsSlugRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/shop/$category': {
      id: '/legacy/shop/$category'
      path: '/shop/$category'
      fullPath: '/legacy/shop/$category'
      preLoaderRoute: typeof LegacyShopCategoryRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/product/$slug': {
      id: '/legacy/product/$slug'
      path: '/product/$slug'
      fullPath: '/legacy/product/$slug'
      preLoaderRoute: typeof LegacyProductSlugRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/orgs/$org': {
      id: '/legacy/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/legacy/orgs/$org'
      preLoaderRoute: typeof LegacyOrgsOrgRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/center-grove/sponsors/$slug': {
      id: '/center-grove/sponsors/$slug'
      path: '/sponsors/$slug'
      fullPath: '/center-grove/sponsors/$slug'
      preLoaderRoute: typeof CenterGroveSponsorsSlugRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/center-grove/shop/$category': {
      id: '/center-grove/shop/$category'
      path: '/shop/$category'
      fullPath: '/center-grove/shop/$category'
      preLoaderRoute: typeof CenterGroveShopCategoryRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/center-grove/product/$slug': {
      id: '/center-grove/product/$slug'
      path: '/product/$slug'
      fullPath: '/center-grove/product/$slug'
      preLoaderRoute: typeof CenterGroveProductSlugRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/center-grove/orgs/$org': {
      id: '/center-grove/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/center-grove/orgs/$org'
      preLoaderRoute: typeof CenterGroveOrgsOrgRouteImport
      parentRoute: typeof CenterGroveRoute
    }
    '/butler/teams/$sport': {
      id: '/butler/teams/$sport'
      path: '/teams/$sport'
      fullPath: '/butler/teams/$sport'
      preLoaderRoute: typeof ButlerTeamsSportRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/butler/sponsors/$slug': {
      id: '/butler/sponsors/$slug'
      path: '/sponsors/$slug'
      fullPath: '/butler/sponsors/$slug'
      preLoaderRoute: typeof ButlerSponsorsSlugRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/butler/shop/$category': {
      id: '/butler/shop/$category'
      path: '/shop/$category'
      fullPath: '/butler/shop/$category'
      preLoaderRoute: typeof ButlerShopCategoryRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/butler/product/$slug': {
      id: '/butler/product/$slug'
      path: '/product/$slug'
      fullPath: '/butler/product/$slug'
      preLoaderRoute: typeof ButlerProductSlugRouteImport
      parentRoute: typeof ButlerRoute
    }
    '/assa/sponsors/$slug': {
      id: '/assa/sponsors/$slug'
      path: '/sponsors/$slug'
      fullPath: '/assa/sponsors/$slug'
      preLoaderRoute: typeof AssaSponsorsSlugRouteImport
      parentRoute: typeof AssaRoute
    }
    '/assa/shop/$category': {
      id: '/assa/shop/$category'
      path: '/shop/$category'
      fullPath: '/assa/shop/$category'
      preLoaderRoute: typeof AssaShopCategoryRouteImport
      parentRoute: typeof AssaRoute
    }
    '/assa/product/$slug': {
      id: '/assa/product/$slug'
      path: '/product/$slug'
      fullPath: '/assa/product/$slug'
      preLoaderRoute: typeof AssaProductSlugRouteImport
      parentRoute: typeof AssaRoute
    }
    '/assa/orgs/$org': {
      id: '/assa/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/assa/orgs/$org'
      preLoaderRoute: typeof AssaOrgsOrgRouteImport
      parentRoute: typeof AssaRoute
    }
    '/legacy/orgs/$org/$team': {
      id: '/legacy/orgs/$org/$team'
      path: '/$team'
      fullPath: '/legacy/orgs/$org/$team'
      preLoaderRoute: typeof LegacyOrgsOrgTeamRouteImport
      parentRoute: typeof LegacyOrgsOrgRoute
    }
    '/center-grove/sponsors/$slug/claim': {
      id: '/center-grove/sponsors/$slug/claim'
      path: '/claim'
      fullPath: '/center-grove/sponsors/$slug/claim'
      preLoaderRoute: typeof CenterGroveSponsorsSlugClaimRouteImport
      parentRoute: typeof CenterGroveSponsorsSlugRoute
    }
    '/center-grove/orgs/$org/$team': {
      id: '/center-grove/orgs/$org/$team'
      path: '/$team'
      fullPath: '/center-grove/orgs/$org/$team'
      preLoaderRoute: typeof CenterGroveOrgsOrgTeamRouteImport
      parentRoute: typeof CenterGroveOrgsOrgRoute
    }
    '/butler/teams/$sport/$player': {
      id: '/butler/teams/$sport/$player'
      path: '/$player'
      fullPath: '/butler/teams/$sport/$player'
      preLoaderRoute: typeof ButlerTeamsSportPlayerRouteImport
      parentRoute: typeof ButlerTeamsSportRoute
    }
    '/butler/sponsors/$slug/claim': {
      id: '/butler/sponsors/$slug/claim'
      path: '/claim'
      fullPath: '/butler/sponsors/$slug/claim'
      preLoaderRoute: typeof ButlerSponsorsSlugClaimRouteImport
      parentRoute: typeof ButlerSponsorsSlugRoute
    }
    '/assa/orgs/$org/$team': {
      id: '/assa/orgs/$org/$team'
      path: '/$team'
      fullPath: '/assa/orgs/$org/$team'
      preLoaderRoute: typeof AssaOrgsOrgTeamRouteImport
      parentRoute: typeof AssaOrgsOrgRoute
    }
    '/legacy/orgs/$org/$team/$player': {
      id: '/legacy/orgs/$org/$team/$player'
      path: '/$player'
      fullPath: '/legacy/orgs/$org/$team/$player'
      preLoaderRoute: typeof LegacyOrgsOrgTeamPlayerRouteImport
      parentRoute: typeof LegacyOrgsOrgTeamRoute
    }
    '/center-grove/orgs/$org/$team/$player': {
      id: '/center-grove/orgs/$org/$team/$player'
      path: '/$player'
      fullPath: '/center-grove/orgs/$org/$team/$player'
      preLoaderRoute: typeof CenterGroveOrgsOrgTeamPlayerRouteImport
      parentRoute: typeof CenterGroveOrgsOrgTeamRoute
    }
    '/assa/orgs/$org/$team/$player': {
      id: '/assa/orgs/$org/$team/$player'
      path: '/$player'
      fullPath: '/assa/orgs/$org/$team/$player'
      preLoaderRoute: typeof AssaOrgsOrgTeamPlayerRouteImport
      parentRoute: typeof AssaOrgsOrgTeamRoute
    }
  }
}

interface AssaOrgsOrgTeamRouteChildren {
  AssaOrgsOrgTeamPlayerRoute: typeof AssaOrgsOrgTeamPlayerRoute
}

const AssaOrgsOrgTeamRouteChildren: AssaOrgsOrgTeamRouteChildren = {
  AssaOrgsOrgTeamPlayerRoute: AssaOrgsOrgTeamPlayerRoute,
}

const AssaOrgsOrgTeamRouteWithChildren = AssaOrgsOrgTeamRoute._addFileChildren(
  AssaOrgsOrgTeamRouteChildren,
)

interface AssaOrgsOrgRouteChildren {
  AssaOrgsOrgTeamRoute: typeof AssaOrgsOrgTeamRouteWithChildren
}

const AssaOrgsOrgRouteChildren: AssaOrgsOrgRouteChildren = {
  AssaOrgsOrgTeamRoute: AssaOrgsOrgTeamRouteWithChildren,
}

const AssaOrgsOrgRouteWithChildren = AssaOrgsOrgRoute._addFileChildren(
  AssaOrgsOrgRouteChildren,
)

interface AssaRouteChildren {
  AssaCartRoute: typeof AssaCartRoute
  AssaTeamCardRoute: typeof AssaTeamCardRoute
  AssaIndexRoute: typeof AssaIndexRoute
  AssaOrgsOrgRoute: typeof AssaOrgsOrgRouteWithChildren
  AssaProductSlugRoute: typeof AssaProductSlugRoute
  AssaShopCategoryRoute: typeof AssaShopCategoryRoute
  AssaSponsorsSlugRoute: typeof AssaSponsorsSlugRoute
  AssaOrgsIndexRoute: typeof AssaOrgsIndexRoute
  AssaShopIndexRoute: typeof AssaShopIndexRoute
  AssaSponsorsIndexRoute: typeof AssaSponsorsIndexRoute
}

const AssaRouteChildren: AssaRouteChildren = {
  AssaCartRoute: AssaCartRoute,
  AssaTeamCardRoute: AssaTeamCardRoute,
  AssaIndexRoute: AssaIndexRoute,
  AssaOrgsOrgRoute: AssaOrgsOrgRouteWithChildren,
  AssaProductSlugRoute: AssaProductSlugRoute,
  AssaShopCategoryRoute: AssaShopCategoryRoute,
  AssaSponsorsSlugRoute: AssaSponsorsSlugRoute,
  AssaOrgsIndexRoute: AssaOrgsIndexRoute,
  AssaShopIndexRoute: AssaShopIndexRoute,
  AssaSponsorsIndexRoute: AssaSponsorsIndexRoute,
}

const AssaRouteWithChildren = AssaRoute._addFileChildren(AssaRouteChildren)

interface ButlerSponsorsSlugRouteChildren {
  ButlerSponsorsSlugClaimRoute: typeof ButlerSponsorsSlugClaimRoute
}

const ButlerSponsorsSlugRouteChildren: ButlerSponsorsSlugRouteChildren = {
  ButlerSponsorsSlugClaimRoute: ButlerSponsorsSlugClaimRoute,
}

const ButlerSponsorsSlugRouteWithChildren =
  ButlerSponsorsSlugRoute._addFileChildren(ButlerSponsorsSlugRouteChildren)

interface ButlerTeamsSportRouteChildren {
  ButlerTeamsSportPlayerRoute: typeof ButlerTeamsSportPlayerRoute
}

const ButlerTeamsSportRouteChildren: ButlerTeamsSportRouteChildren = {
  ButlerTeamsSportPlayerRoute: ButlerTeamsSportPlayerRoute,
}

const ButlerTeamsSportRouteWithChildren =
  ButlerTeamsSportRoute._addFileChildren(ButlerTeamsSportRouteChildren)

interface ButlerRouteChildren {
  ButlerCartRoute: typeof ButlerCartRoute
  ButlerTeamCardRoute: typeof ButlerTeamCardRoute
  ButlerIndexRoute: typeof ButlerIndexRoute
  ButlerProductSlugRoute: typeof ButlerProductSlugRoute
  ButlerShopCategoryRoute: typeof ButlerShopCategoryRoute
  ButlerSponsorsSlugRoute: typeof ButlerSponsorsSlugRouteWithChildren
  ButlerTeamsSportRoute: typeof ButlerTeamsSportRouteWithChildren
  ButlerShopIndexRoute: typeof ButlerShopIndexRoute
  ButlerSponsorsIndexRoute: typeof ButlerSponsorsIndexRoute
  ButlerTeamsIndexRoute: typeof ButlerTeamsIndexRoute
}

const ButlerRouteChildren: ButlerRouteChildren = {
  ButlerCartRoute: ButlerCartRoute,
  ButlerTeamCardRoute: ButlerTeamCardRoute,
  ButlerIndexRoute: ButlerIndexRoute,
  ButlerProductSlugRoute: ButlerProductSlugRoute,
  ButlerShopCategoryRoute: ButlerShopCategoryRoute,
  ButlerSponsorsSlugRoute: ButlerSponsorsSlugRouteWithChildren,
  ButlerTeamsSportRoute: ButlerTeamsSportRouteWithChildren,
  ButlerShopIndexRoute: ButlerShopIndexRoute,
  ButlerSponsorsIndexRoute: ButlerSponsorsIndexRoute,
  ButlerTeamsIndexRoute: ButlerTeamsIndexRoute,
}

const ButlerRouteWithChildren =
  ButlerRoute._addFileChildren(ButlerRouteChildren)

interface CenterGroveOrgsOrgTeamRouteChildren {
  CenterGroveOrgsOrgTeamPlayerRoute: typeof CenterGroveOrgsOrgTeamPlayerRoute
}

const CenterGroveOrgsOrgTeamRouteChildren: CenterGroveOrgsOrgTeamRouteChildren =
  {
    CenterGroveOrgsOrgTeamPlayerRoute: CenterGroveOrgsOrgTeamPlayerRoute,
  }

const CenterGroveOrgsOrgTeamRouteWithChildren =
  CenterGroveOrgsOrgTeamRoute._addFileChildren(
    CenterGroveOrgsOrgTeamRouteChildren,
  )

interface CenterGroveOrgsOrgRouteChildren {
  CenterGroveOrgsOrgTeamRoute: typeof CenterGroveOrgsOrgTeamRouteWithChildren
}

const CenterGroveOrgsOrgRouteChildren: CenterGroveOrgsOrgRouteChildren = {
  CenterGroveOrgsOrgTeamRoute: CenterGroveOrgsOrgTeamRouteWithChildren,
}

const CenterGroveOrgsOrgRouteWithChildren =
  CenterGroveOrgsOrgRoute._addFileChildren(CenterGroveOrgsOrgRouteChildren)

interface CenterGroveSponsorsSlugRouteChildren {
  CenterGroveSponsorsSlugClaimRoute: typeof CenterGroveSponsorsSlugClaimRoute
}

const CenterGroveSponsorsSlugRouteChildren: CenterGroveSponsorsSlugRouteChildren =
  {
    CenterGroveSponsorsSlugClaimRoute: CenterGroveSponsorsSlugClaimRoute,
  }

const CenterGroveSponsorsSlugRouteWithChildren =
  CenterGroveSponsorsSlugRoute._addFileChildren(
    CenterGroveSponsorsSlugRouteChildren,
  )

interface CenterGroveRouteChildren {
  CenterGroveCartRoute: typeof CenterGroveCartRoute
  CenterGroveTeamCardRoute: typeof CenterGroveTeamCardRoute
  CenterGroveIndexRoute: typeof CenterGroveIndexRoute
  CenterGroveOrgsOrgRoute: typeof CenterGroveOrgsOrgRouteWithChildren
  CenterGroveProductSlugRoute: typeof CenterGroveProductSlugRoute
  CenterGroveShopCategoryRoute: typeof CenterGroveShopCategoryRoute
  CenterGroveSponsorsSlugRoute: typeof CenterGroveSponsorsSlugRouteWithChildren
  CenterGroveOrgsIndexRoute: typeof CenterGroveOrgsIndexRoute
  CenterGroveShopIndexRoute: typeof CenterGroveShopIndexRoute
  CenterGroveSponsorsIndexRoute: typeof CenterGroveSponsorsIndexRoute
}

const CenterGroveRouteChildren: CenterGroveRouteChildren = {
  CenterGroveCartRoute: CenterGroveCartRoute,
  CenterGroveTeamCardRoute: CenterGroveTeamCardRoute,
  CenterGroveIndexRoute: CenterGroveIndexRoute,
  CenterGroveOrgsOrgRoute: CenterGroveOrgsOrgRouteWithChildren,
  CenterGroveProductSlugRoute: CenterGroveProductSlugRoute,
  CenterGroveShopCategoryRoute: CenterGroveShopCategoryRoute,
  CenterGroveSponsorsSlugRoute: CenterGroveSponsorsSlugRouteWithChildren,
  CenterGroveOrgsIndexRoute: CenterGroveOrgsIndexRoute,
  CenterGroveShopIndexRoute: CenterGroveShopIndexRoute,
  CenterGroveSponsorsIndexRoute: CenterGroveSponsorsIndexRoute,
}

const CenterGroveRouteWithChildren = CenterGroveRoute._addFileChildren(
  CenterGroveRouteChildren,
)

interface LegacyOrgsOrgTeamRouteChildren {
  LegacyOrgsOrgTeamPlayerRoute: typeof LegacyOrgsOrgTeamPlayerRoute
}

const LegacyOrgsOrgTeamRouteChildren: LegacyOrgsOrgTeamRouteChildren = {
  LegacyOrgsOrgTeamPlayerRoute: LegacyOrgsOrgTeamPlayerRoute,
}

const LegacyOrgsOrgTeamRouteWithChildren =
  LegacyOrgsOrgTeamRoute._addFileChildren(LegacyOrgsOrgTeamRouteChildren)

interface LegacyOrgsOrgRouteChildren {
  LegacyOrgsOrgTeamRoute: typeof LegacyOrgsOrgTeamRouteWithChildren
}

const LegacyOrgsOrgRouteChildren: LegacyOrgsOrgRouteChildren = {
  LegacyOrgsOrgTeamRoute: LegacyOrgsOrgTeamRouteWithChildren,
}

const LegacyOrgsOrgRouteWithChildren = LegacyOrgsOrgRoute._addFileChildren(
  LegacyOrgsOrgRouteChildren,
)

interface LegacyRouteChildren {
  LegacyCartRoute: typeof LegacyCartRoute
  LegacyTeamCardRoute: typeof LegacyTeamCardRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
  LegacyOrgsOrgRoute: typeof LegacyOrgsOrgRouteWithChildren
  LegacyProductSlugRoute: typeof LegacyProductSlugRoute
  LegacyShopCategoryRoute: typeof LegacyShopCategoryRoute
  LegacySponsorsSlugRoute: typeof LegacySponsorsSlugRoute
  LegacyOrgsIndexRoute: typeof LegacyOrgsIndexRoute
  LegacyShopIndexRoute: typeof LegacyShopIndexRoute
  LegacySponsorsIndexRoute: typeof LegacySponsorsIndexRoute
}

const LegacyRouteChildren: LegacyRouteChildren = {
  LegacyCartRoute: LegacyCartRoute,
  LegacyTeamCardRoute: LegacyTeamCardRoute,
  LegacyIndexRoute: LegacyIndexRoute,
  LegacyOrgsOrgRoute: LegacyOrgsOrgRouteWithChildren,
  LegacyProductSlugRoute: LegacyProductSlugRoute,
  LegacyShopCategoryRoute: LegacyShopCategoryRoute,
  LegacySponsorsSlugRoute: LegacySponsorsSlugRoute,
  LegacyOrgsIndexRoute: LegacyOrgsIndexRoute,
  LegacyShopIndexRoute: LegacyShopIndexRoute,
  LegacySponsorsIndexRoute: LegacySponsorsIndexRoute,
}

const LegacyRouteWithChildren =
  LegacyRoute._addFileChildren(LegacyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssaRoute: AssaRouteWithChildren,
  ButlerRoute: ButlerRouteWithChildren,
  CenterGroveRoute: CenterGroveRouteWithChildren,
  LegacyRoute: LegacyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
